# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzCwznTpz-oYDcc6iOK3OFdDC-MpDps1
"""

import telebot
import os


TOKEN = os.getenv("TOKEN", "8180402827:AAEV81tDFCuZFQR-zijEflP_jji2bu4dX-w")
bot = telebot.TeleBot(TOKEN)

# Хранилище данных пользователей
user_data = {}

# Вопросы с жёстким, взрослым юмором
QUESTIONS = [
    {
        "text": "Ты до сих пор учишься, потому что...",
        "options": [
            ("...не представляешь, чем ещё заниматься", {"lost": +2, "burnout": +1}),
            ("...родители гордятся — а ты не хочешь их разочаровывать", {"investment": +2, "lost": +1}),
            ("...без корочки вообще никуда не берут", {"alcoholic": +2, "investment": +1}),
            ("...просто боишься, что в реальной жизни будет хуже", {"burnout": +2, "alcoholic": +1})
        ]
    },
    {
        "text": "Когда ты в последний раз верил, что всё наладится?",
        "options": [
            ("Когда поступил. Больше не верю", {"lost": +2}),
            ("Вчера. Сегодня получил письмо от банка", {"investment": +2}),
            ("Не помню. Наверное, в школе", {"burnout": +2}),
            ("Каждое утро. И каждый вечер разочаровываюсь", {"alcoholic": +2})
        ]
    },
    {
        "text": "Ты бы бросил учёбу, если бы...",
        "options": [
            ("...не боялся стать \"неудачником\" в глазах других", {"lost": +2}),
            ("...не был должен за общагу и кредит", {"investment": +2}),
            ("...знал, что смогу выжить без диплома", {"burnout": +2}),
            ("...осталась хоть капля энергии на побег", {"alcoholic": +2})
        ]
    }
]

ARCHETYPES = {
    "lost": {
        "title": "Ты — Потерянное поколение с дипломом",
        "text": "Учился 5 лет. Работаешь за 40 тыс. в call-центре. Твой диплом — лучший пресс-папье в мире.",
        "image": "https://i.imgur.com/3VnRf9P.jpg"
    },
    "investment": {
        "title": "Ты — Инвестиция в ничто",
        "text": "Родители влезли в кредит, чтобы ты \"стал кем-то\". Теперь ты — кто-то, кто должен 800 тыс. банку.",
        "image": "https://i.imgur.com/mJqKfGd.jpg"
    },
    "burnout": {
        "title": "Ты — Статистика выгорания",
        "text": "Ты не ушёл из вуза. Ты просто перестал реагировать. Тебя можно вызывать — ты придёшь. Тебя можно не замечать — ты не обидишься.",
        "image": "https://i.imgur.com/8zWbDcL.jpg"
    },
    "alcoholic": {
        "title": "Ты — Будущий алкоголик с красным дипломом",
        "text": "Сначала думал: «Выпью на выпускном». Теперь: «Выпью, чтобы вспомнить, зачем я вообще начал».",
        "image": "https://i.imgur.com/rYxVt4A.jpg"
    }
}

def reset_user(uid):
    """Инициализирует состояние пользователя"""
    user_data[uid] = {
        "step": 0,
        "scores": {key: 0 for key in ARCHETYPES}
    }

@bot.message_handler(commands=['start'])
def start_handler(message):
    reset_user(message.chat.id)
    send_question(message.chat.id, 0)

def send_question(uid, step):
    if step >= len(QUESTIONS):
        show_result(uid)
        return

    q = QUESTIONS[step]
    markup = telebot.types.InlineKeyboardMarkup()
    for idx, (text, _) in enumerate(q["options"]):
        markup.add(telebot.types.InlineKeyboardButton(text, callback_data=f"q_{step}_{idx}"))

    bot.send_message(uid, f"🫠 Вопрос {step + 1}/3\n\n{q['text']}", reply_markup=markup)

@bot.callback_query_handler(func=lambda call: call.data.startswith("q_"))
def handle_answer(call):
    uid = call.message.chat.id

    # Инициализируем пользователя, если первый запуск
    if uid not in user_data:
        reset_user(uid)

    # Парсим ответ
    parts = call.data.split("_")
    step = int(parts[1])
    option_idx = int(parts[2])

    # Начисляем баллы
    effect = QUESTIONS[step]["options"][option_idx][1]
    for key, points in effect.items():
        user_data[uid]["scores"][key] += points

    # Удаляем предыдущее сообщение (чисто)
    try:
        bot.delete_message(uid, call.message.message_id)
    except:
        pass  # Игнорируем ошибку, если сообщение уже удалено

    bot.answer_callback_query(call.id)
    send_question(uid, step + 1)

def show_result(uid):
    scores = user_data[uid]["scores"]
    best_type = max(scores, key=scores.get)
    data = ARCHETYPES[best_type]

    caption = (
        f"### {data['title']}\n\n"
        f"{data['text']}\n\n"
        f"📤 Пройти тест: @{bot.get_me().username}"
    )

    bot.send_photo(uid, data["image"], caption=caption)

# Запуск бота
if __name__ == "__main__":
    bot.polling(none_stop=True)